# CMake generated Testfile for 
# Source directory: /home/angel/catkin_ws/src/slam_gmapping-hydro-devel/gmapping
# Build directory: /home/angel/catkin_ws/src/slam_gmapping-hydro-devel/gmapping-build
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(_ctest_gmapping_rostest_test_basic_localization_stage.launch "/home/angel/catkin_ws/src/slam_gmapping-hydro-devel/gmapping-build/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/indigo/share/catkin/cmake/test/run_tests.py" "/home/angel/catkin_ws/src/slam_gmapping-hydro-devel/gmapping-build/test_results/gmapping/rostest-test_basic_localization_stage.xml" "--return-code" "/opt/ros/indigo/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/angel/catkin_ws/src/slam_gmapping-hydro-devel/gmapping --package=gmapping --results-filename test_basic_localization_stage.xml --results-base-dir \"/home/angel/catkin_ws/src/slam_gmapping-hydro-devel/gmapping-build/test_results\" /home/angel/catkin_ws/src/slam_gmapping-hydro-devel/gmapping/test/basic_localization_stage.launch ")
ADD_TEST(_ctest_gmapping_rostest_test_basic_localization_stage_replay.launch "/home/angel/catkin_ws/src/slam_gmapping-hydro-devel/gmapping-build/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/indigo/share/catkin/cmake/test/run_tests.py" "/home/angel/catkin_ws/src/slam_gmapping-hydro-devel/gmapping-build/test_results/gmapping/rostest-test_basic_localization_stage_replay.xml" "--return-code" "/opt/ros/indigo/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/angel/catkin_ws/src/slam_gmapping-hydro-devel/gmapping --package=gmapping --results-filename test_basic_localization_stage_replay.xml --results-base-dir \"/home/angel/catkin_ws/src/slam_gmapping-hydro-devel/gmapping-build/test_results\" /home/angel/catkin_ws/src/slam_gmapping-hydro-devel/gmapping/test/basic_localization_stage_replay.launch ")
ADD_TEST(_ctest_gmapping_rostest_test_basic_localization_stage_replay2.launch "/home/angel/catkin_ws/src/slam_gmapping-hydro-devel/gmapping-build/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/indigo/share/catkin/cmake/test/run_tests.py" "/home/angel/catkin_ws/src/slam_gmapping-hydro-devel/gmapping-build/test_results/gmapping/rostest-test_basic_localization_stage_replay2.xml" "--return-code" "/opt/ros/indigo/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/angel/catkin_ws/src/slam_gmapping-hydro-devel/gmapping --package=gmapping --results-filename test_basic_localization_stage_replay2.xml --results-base-dir \"/home/angel/catkin_ws/src/slam_gmapping-hydro-devel/gmapping-build/test_results\" /home/angel/catkin_ws/src/slam_gmapping-hydro-devel/gmapping/test/basic_localization_stage_replay2.launch ")
ADD_TEST(_ctest_gmapping_rostest_test_basic_localization_symmetry.launch "/home/angel/catkin_ws/src/slam_gmapping-hydro-devel/gmapping-build/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/indigo/share/catkin/cmake/test/run_tests.py" "/home/angel/catkin_ws/src/slam_gmapping-hydro-devel/gmapping-build/test_results/gmapping/rostest-test_basic_localization_symmetry.xml" "--return-code" "/opt/ros/indigo/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/angel/catkin_ws/src/slam_gmapping-hydro-devel/gmapping --package=gmapping --results-filename test_basic_localization_symmetry.xml --results-base-dir \"/home/angel/catkin_ws/src/slam_gmapping-hydro-devel/gmapping-build/test_results\" /home/angel/catkin_ws/src/slam_gmapping-hydro-devel/gmapping/test/basic_localization_symmetry.launch ")
ADD_TEST(_ctest_gmapping_rostest_test_basic_localization_upside_down.launch "/home/angel/catkin_ws/src/slam_gmapping-hydro-devel/gmapping-build/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/indigo/share/catkin/cmake/test/run_tests.py" "/home/angel/catkin_ws/src/slam_gmapping-hydro-devel/gmapping-build/test_results/gmapping/rostest-test_basic_localization_upside_down.xml" "--return-code" "/opt/ros/indigo/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/angel/catkin_ws/src/slam_gmapping-hydro-devel/gmapping --package=gmapping --results-filename test_basic_localization_upside_down.xml --results-base-dir \"/home/angel/catkin_ws/src/slam_gmapping-hydro-devel/gmapping-build/test_results\" /home/angel/catkin_ws/src/slam_gmapping-hydro-devel/gmapping/test/basic_localization_upside_down.launch ")
ADD_TEST(_ctest_gmapping_rostest_test_basic_localization_laser_different_beamcount.test "/home/angel/catkin_ws/src/slam_gmapping-hydro-devel/gmapping-build/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/indigo/share/catkin/cmake/test/run_tests.py" "/home/angel/catkin_ws/src/slam_gmapping-hydro-devel/gmapping-build/test_results/gmapping/rostest-test_basic_localization_laser_different_beamcount.xml" "--return-code" "/opt/ros/indigo/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/angel/catkin_ws/src/slam_gmapping-hydro-devel/gmapping --package=gmapping --results-filename test_basic_localization_laser_different_beamcount.xml --results-base-dir \"/home/angel/catkin_ws/src/slam_gmapping-hydro-devel/gmapping-build/test_results\" /home/angel/catkin_ws/src/slam_gmapping-hydro-devel/gmapping/test/basic_localization_laser_different_beamcount.test ")
SUBDIRS(gtest)
